### ISSUE TITLE
Gradle frissítése

### ISSUE THREAD

**Issue by pethesdaniel** [BME-MIT-IET/iet-hf-2022-teamwork#1]
A gradle verzió felfrissítése 2.0-ról egy frisebb változatra, a modern fejlesztői eszközök támogatásához

**Comment by pethesdaniel** [comment]
A grade 7.x tesztelése után kiderült, hogy túl módosítást kellene végrehajtani a build.gradle file-on.

**Comment by pethesdaniel** [comment]
Javasolt verzió 6.x

**Comment by pethesdaniel** [comment]
[d8c53ac](https://github.com/BME-MIT-IET/iet-hf-2022-teamwork/commit/d8c53ac494c6daac2c7e347aca0efa3d894079e5) committal frissítettem a gradle verziót.

**Comment by kalicsadam** [comment]
A Gradle verzió 6.9.2-re sikeresen frissítve lett és megfelelően működik a parancssorban és fejlesztői környezetben is.
