### ISSUE TITLE
GitHub Actions beüzemelése

### ISSUE THREAD

**Issue by pethesdaniel** [BME-MIT-IET/iet-hf-2022-teamwork#2]
GitHub Actions segítségével buildek autómatizálása

**Comment by pethesdaniel** [comment]
[b1b377b](https://github.com/BME-MIT-IET/iet-hf-2022-teamwork/commit/b1b377b1c278942e7b04b3e07628ff6044780964)
A GH Release helyett a pipeline mostmár teszteket futtat.

**Comment by kalicsadam** [comment]
A GitHub Actions sikeresen build-eli a projektet és lefuttatja a testeket.
