### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére

### ISSUE THREAD

**Issue by pethesdaniel** [BME-MIT-IET/iet-hf-2022-teamwork#3]
Kód manuális átvizsgálása.

**Comment by kalicsadam** [comment]
Átnéztem a kódot és nem találtam elvi hibákat.

**Comment by pethesdaniel** [comment]
A kód átvizsgálása során nem találtam hibát.

**Comment by Haragos99** [comment]
Átvvizsgáltam a kódot és nem találtam hibaát

**Comment by mariiscute** [comment]
A kódállomány átvizsgálása során nem találtam hibákat
