### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarCloud)

### ISSUE THREAD

**Issue by pethesdaniel** [BME-MIT-IET/iet-hf-2022-teamwork#4]

**Comment by kalicsadam** [comment]
A sonarcloud statikus analízis során két hibát találtunk, melyből az egyik egy potenciális NullPointerException.
Nem történt egységes megállapodás a bug kijavításáról, azonban egy Issue-t létrehoztunk.

**Comment by kalicsadam** [comment]
See: #12
