### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása vagy exploratory testing

### ISSUE THREAD

**Issue by pethesdaniel** [BME-MIT-IET/iet-hf-2022-teamwork#6]
Teszt osztályok létrehozása, egyszerű adatszerkezet, majd ezekkel szerializálása és az eredemény vizsgálata. Readmeben való dokumentálás.

**Comment by pethesdaniel** [comment]
Az eredmények a Wikiben találhatóak: [Exploratory testing](https://github.com/BME-MIT-IET/iet-hf-2022-teamwork/wiki/Exploratory-testing)

**Comment by Haragos99** [comment]
Megnéztem a kódot és rendben volt
